language: go

go:
  - 1.15.x

env:
  - CGO_CFLAGS_ALLOW="-Xpreprocessor"

matrix:
  include:
    - os: osx
      osx_image: xcode12.2

    - os: osx
      osx_image: xcode11.3

    - os: linux
      dist: bionic

    - os: linux
      dist: focal

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:tonimelisma/ppa; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install libvips-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install vips; fi
  - go get github.com/mattn/goveralls

script:
  - make test
  - $GOPATH/bin/goveralls -service=travis-ci